x = input().strip(" ")
x = x.strip("{}")
x = x.strip(" ")
x = x.split(",")
x = list(map( lambda e: e.lstrip(), x))
x = list(map( lambda e: e.rstrip(), x))
x = list(set(x))
if(x == ['']): print("0")
else: print(len(x))